export const GAME = {
	STATUS: {
		IN_PROGRESS: 'IN_PROGRESS', 
		PLAYER_WINS: 'PLAYER_WINS',
		DEALER_WINS: 'DEALER_WINS',
		DRAW: 'DRAW',
	},
};

export const PLAYERS = {
	DEALER: 'DEALER',
	PLAYER: 'PLAYER',
};